#!/usr/bin/env python3
"""Create local secrets/config without changing or restarting the running PBX."""

import os
from pathlib import Path
import re
import secrets
import shlex

ROOT = Path(__file__).resolve().parent


def main():
    os.umask(0o077)
    env_path = ROOT / ".env"
    if not env_path.exists():
        template = (ROOT / ".env.example").read_text()
        template = template.replace("AMI_SECRET=GENERATE_ME", "AMI_SECRET=" + secrets.token_urlsafe(32))
        with env_path.open("x") as output:
            output.write(template)
    values = {}
    for line in env_path.read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            tokens = shlex.split(value, comments=True)
            values[key.strip()] = " ".join(tokens)
    secret = values.get("AMI_SECRET", "")
    user = values.get("AMI_USER", "huddle-phone")
    port = values.get("AMI_PORT", "5038")
    if not re.fullmatch(r"[A-Za-z0-9_-]{24,128}", secret):
        raise SystemExit("AMI_SECRET must contain 24–128 letters, numbers, hyphens or underscores")
    if not re.fullmatch(r"[A-Za-z0-9_-]+", user) or not port.isdigit() or not 1024 <= int(port) <= 65535:
        raise SystemExit("Invalid AMI_USER or AMI_PORT")
    directory = ROOT / "generated"
    directory.mkdir(exist_ok=True)
    path = directory / "manager.conf"
    path.write_text(f"""; Generated by huddle-phone/configure.py; contains a secret.
[general]
enabled=yes
webenabled=no
bindaddr=127.0.0.1
port={port}

[{user}]
secret={secret}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
read=call
write=originate,call
""")
    env_path.chmod(0o600)
    path.chmod(0o600)
    print("Created/updated huddle-phone/.env and generated/manager.conf. No running services changed.")
    print("Fill in Slack user session settings in .env, then follow huddle-phone/README.md.")


if __name__ == "__main__":
    main()
